<a href="https://colab.research.google.com/github/zsx29/Colab/blob/main/2_Numpy%EC%8B%A4%EC%8A%B5%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
"""

  날짜 : 2021-07-05
  이름 : 박재형
  내용 : Numpy 실습하기

"""
import numpy as np  

In [16]:
# Numpy 자료구조 - 벡터

v1 = np.array([1, 2, 3, 4, 5])
print("v1 :", v1)

v2 = np.arange(5)
print("v2 :", v2)

v3 = np.arange(10)
print("v3 :", v3)

v4 = [1, 2, 3, 4, 5]
print("v4 :", len(v4))
print("v1 :", len(v1))


v1 : [1 2 3 4 5]
v2 : [0 1 2 3 4]
v3 : [0 1 2 3 4 5 6 7 8 9]
v4 : 5
v1 : 5


In [24]:
# 0 ~ 1 사이의 임의의 실수
rand1 = np.random.rand(100)
print(rand1)


# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
print(rand2)

# 0 ~ 9 사이의 임의의 정수
rand3 = np.random.randint(10)
print(rand3)


[0.01626179 0.69918715 0.00369803 0.76098165 0.38829964 0.48774119
 0.30211817 0.72171285 0.5496731  0.459655   0.00315524 0.81726841
 0.92066626 0.23216603 0.64040132 0.65036375 0.95359377 0.34945487
 0.2739416  0.7800145  0.7721292  0.42568966 0.34426532 0.23058453
 0.75831031 0.79446273 0.3064646  0.04138992 0.23231764 0.13958892
 0.38638608 0.78462663 0.76761912 0.04502018 0.41950783 0.41403786
 0.93545382 0.753835   0.13125176 0.24306397 0.17312845 0.04143383
 0.10220672 0.00116165 0.38343982 0.19387543 0.34861653 0.09334899
 0.93834565 0.08124916 0.82816694 0.85367724 0.10277099 0.90892337
 0.50154265 0.25045102 0.42364872 0.97671779 0.93239738 0.77770943
 0.00925531 0.8013209  0.32952063 0.83642943 0.87291632 0.09851483
 0.00987309 0.36312838 0.3613817  0.46484356 0.94233982 0.42126579
 0.7046967  0.52594343 0.03533192 0.49634614 0.25973942 0.81602399
 0.35799199 0.93878779 0.0343657  0.13515025 0.75786212 0.50670041
 0.69669286 0.71469641 0.9476868  0.32749569 0.83571224 0.2329

In [31]:
# Numpy 자료구조 - 행렬
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [37]:
# 전치행렬
m1.T
print(m1.T)
print(m2.transpose())

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
# 단위행렬
e1 = np.identity(2)
e2 = np.identity(3)
e3 = np.identity(4)
print(e1)
print(e2)
print(e3)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
# 역행렬
im1 = np.linalg.inv(m1)  # inverse

print(im1)
print(m1)
result = m1.dot(im1)
print(result.round()) 

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 2]
 [3 4]]
[[1. 0.]
 [0. 1.]]


In [57]:
# 행렬 인덱싱
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)

print(matrix[1, 2])
print(matrix[0, :])
print(matrix[:, 0])
print(matrix[2:0, 0:2])
print(matrix[:, 0:2])
print(matrix[1:3, 3:1])







[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[1 2 3 4]
[1 5 9]
[]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[]
